# DO NOT EDIT - This file is automatically generated
# Make changes to Manifest.txt and/or Rakefile and regenerate
# -*- encoding: utf-8 -*-
# stub: fixme 1.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "fixme".freeze
  s.version = "1.0.0".freeze

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.metadata = { "bug_tracker_uri" => "https://github.com/copiousfreetime/fixme/issues", "changelog_uri" => "https://github.com/copiousfreetime/fixme/blob/master/HISTORY.md", "homepage_uri" => "https://github.com/copiousfreetime/fixme", "label" => "fixme", "rubygems_mfa_required" => "true", "source_code_uri" => "https://github.com/copiousfreetime/fixme" } if s.respond_to? :metadata=
  s.require_paths = ["lib".freeze]
  s.authors = ["Jeremy Hinegardner".freeze]
  s.bindir = "exe".freeze
  s.date = "2024-04-28"
  s.description = "WRITE A DESCRTIPTION (FIXME)".freeze
  s.email = "jeremy@copiousfreetime.org".freeze
  s.extra_rdoc_files = ["CONTRIBUTING.md".freeze, "HISTORY.md".freeze, "LICENSE.txt".freeze, "Manifest.txt".freeze, "README.md".freeze]
  s.files = ["CONTRIBUTING.md".freeze, "HISTORY.md".freeze, "LICENSE.txt".freeze, "Manifest.txt".freeze, "README.md".freeze, "lib/fixme.rb".freeze]
  s.homepage = "http://github.com/copiousfreetime/fixme".freeze
  s.licenses = ["MIT".freeze]
  s.rdoc_options = ["--main".freeze, "README.md".freeze, "--markup".freeze, "tomdoc".freeze]
  s.required_ruby_version = Gem::Requirement.new(">= 3.0.0".freeze)
  s.rubygems_version = "3.5.9".freeze
  s.summary = "WRITE A DESCRTIPTION (FIXME)".freeze
end
